genomes:
    NC_001609: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001609/NC_001609.fasta
    NC_001998: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001998/NC_001998.fasta
    NC_001954: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001954/NC_001954.fasta
    NC_001902: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001902/NC_001902.fasta
    NC_001423: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001423/NC_001423.fasta
    NC_001335: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001335/NC_001335.fasta
    NC_001895: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001895/NC_001895.fasta
    NC_001332: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001332/NC_001332.fasta
    NC_001365: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001365/NC_001365.fasta
    NC_001825: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001825/NC_001825.fasta