genomes:
  NC_001270: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001270/NC_001270.fasta
  NC_001271: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001271/NC_001271.fasta
  NC_001317: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001317/NC_001317.fasta
  NC_001330: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001330/NC_001330.fasta
  NC_001331: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001331/NC_001331.fasta
  NC_001332: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001332/NC_001332.fasta
  NC_001335: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001335/NC_001335.fasta
  NC_001338: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001338/NC_001338.fasta
  NC_001341: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001341/NC_001341.fasta
  NC_001365: /home/adela/DefSystems/Phage_genomes/Refseq/single_refseq_genomes/40_GBid/NC_001365/NC_001365.fasta