---
title: "IMG_VR"
author: "Adéla Finstrlová"
date: "2023-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#rm(list=ls(all=TRUE)) ##removes all variables that were stored in rstudio from older projects
#install.packages("car")
library("tidyverse")
# install bioconductor, run with ctrl + enter, when asked "update all/some/none" pres n
#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")
#BiocManager::install("apeglm", ask = FALSE) # update old packages without being prompted
# install DESeq2
#BiocManager::install("DESeq2")
```

```{r variables, include=F}
#Work LMDM-5
#COMP<-"d:/Prace/"
#T420 Lenovo
#COMP<-"d:/Ade/Documents/Uni/Prace/"
#Fujitsu
COMP<-"C:/Users/VEO_lab_0/Documents/Jena/"
```

## 0. Data

```{r read data}
#read data
IMG_data = read.table(paste0(COMP,"DefSystems/DefSysPro/Phage_genomes/IMG_VR/IMGVR_all_Sequence_information-high_confidence.tsv"), header = T, sep = "\t")
#check data
colnames(IMG_data)
# quick length check
hist(IMG_data$Length)

levels(as.factor(str_split_fixed(IMG_data$Host.taxonomy.prediction,";", 2)[,1]))
#works neatly, 
table(as.factor(str_split_fixed(IMG_data$Host.taxonomy.prediction,";", 2)[,1]))


#dplyr count needs name of the column
colnames(data.frame(as.factor(str_split_fixed(IMG_data$Host.taxonomy.prediction,";", 2)[,1])))
count(data.frame(as.factor(str_split_fixed(IMG_data$Host.taxonomy.prediction,";", 2)[,1])), as.factor.str_split_fixed.IMG_data.Host.taxonomy.prediction..)

domain_df <- data.frame(as.factor(str_split_fixed(IMG_data$Host.taxonomy.prediction,";", 2)[,1]))
colnames(domain_df) <- c("domain")

count_domain_df<- count(domain_df, domain)

#change factor leves
levels(count_domain_df$domain) <- c("Unknown", "Archea", "Bacteria")

#add position of the labels
count_domain_df <- count_domain_df %>% 
  arrange(desc(domain)) %>%
  mutate(prop = n / sum(count_domain_df$n) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )

count_domain_df %>% 
  ggplot(aes(fill=domain, y=n, x="")) +
  geom_bar(stat = "identity", width = 1, color="white") +
  coord_polar("y", start=0) +
  theme_void()#+
## position of the text is not functioning
  theme(legend.position="none") +
  geom_text(aes(y = ypos, label = domain), color = "white", size=5) +
  scale_fill_brewer(palette="Set1")

sum(is.na(IMG_data$Estimated.completeness))

#Filter number of viruses based on Topology, completeness and length
IMG_data %>%   
  filter(str_detect(Host.taxonomy.prediction, "d__Bacteria") &
         Topology == "Linear" &
         !is.na(Estimated.completeness) &
         Estimated.completeness > 90 &
           Length > 1
         ) %>% 
    nrow()

#select only viruses with bacterial host
IMG_data %>% 
  filter(str_detect(Host.taxonomy.prediction, "d__Bacteria") &
         Topology == "Provirus" &
         !is.na(Estimated.completeness) &
         Estimated.completeness == 100 &
         Length > 1) %>% 
    nrow()
```

```{r density plot}
# Basic density
IMG_data %>%  
  filter(Estimated.completeness > 90 &
           Length > 25000 &
           Topology == "Linear" ) %>%
  ggplot(aes(x=Length, color=Topology)) + 
  geom_density(size=1.1) +
  xlim(0, 200000) +
  theme_classic()
```

```{r density plot Bacteria}
# Basic density
IMG_data_bacteria %>%  
  filter(Estimated.completeness > 90 &
           Length > 25000 &
           Topology == "Linear" ) %>%
  ggplot(aes(x=Length, color=Topology)) + 
  geom_density(size=1.1) +
  xlim(0, 200000) +
  theme_classic()
```
