#!/bin/bash
#SBATCH --job-name snake_local
#SBATCH --partition=long
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=90
#SBATCH --mem=32768
#SBATCH --output  log/snake_local.%j.out                #%j means job ID
#SBATCH --error   log/snake_local.%j.err
#SBATCH --time=14-00:00:00 #days
#SADABATCH --exclusive=user
#-----------------------------------------------------------------
# Script to rerun pharokka annotation step that failed during the
# first run.

unset SLURM_MEM_PER_CPU SLURM_MEM_PER_GPU SLURM_MEM_PER_NODE

#modules
module load tools/python/3.8

#Commands
cd ~/DefSystems
snakemake --unlock
#snakemake extract_genomes -c all
if [ -f "output/extracted_ok" ]; then
        if [ "$1" == "local" ]; then
                snakemake -c all
        else
                # Quota = 10 hosts, we're using 3 jobs per host + one long
                # (-j) 27/3 = 9 (+ 1 long)
                snakemake -s Snakefile.local -c 93 --keep-going
        fi
else
        echo "ERROR: No output/extracted_ok file exists = Missing correct genomes." >&2
fi
